name: projects
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: AvenirLTStd
      fonts:
        - asset: assets/fonts/AvenirLTStd-Black.ttf
        - asset: assets/fonts/AvenirLTStd-BlackOblique.ttf
        - asset: assets/fonts/AvenirLTStd-Book.ttf
        - asset: assets/fonts/AvenirLTStd-Heavy.ttf
        - asset: assets/fonts/AvenirLTStd-Medium.ttf
        - asset: assets/fonts/AvenirLTStd-Roman.ttf
